services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: owasp-crud-demo
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/${MONGO_DATABASE}

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: